[package]
name = "network-record-replay"
version = "0.1.0"
authors = ["Lind, Niclas <niclas.lind@volvocars.com>"]
edition = "2018"

[lib]
name = "protos"
path = "src/protos/mod.rs"

[dependencies]
grpcio = "0.6.0"
protobuf = "2.17.0"
futures = "0.3.5"

[build-dependencies]
protoc-grpcio = "2.0.0"